<?php 

#Here we get the callback notification which is a json string
$input=file_get_contents('php://input');
$data = json_decode($input);

#Below here we store the relevant notification items

$source=$data->response->source;//This is the phone number that initiated the transaction.

$value=$data->response->value;//This is the amount paid preceded with a KES

$amount=ltrim($value,"KES ");//This is the amount value without the KES you can use this if you wish to perform queries or calculations.

$status=$data->response->status;//This is the transaction status,possible values: Success,Failed

$Metadata=$data->response->requestMetadata->MetadataValue;//This is an example of how you retrieve the attached meta data.You will have to replace the MetadataValue with your actual meta data name as sent ith the request.

$Category=$data->response->Category;//Category of the paymet

$Provider=$data->response->Provider;//Payment Provider in this case MPESA

$providerRefId=$data->response->providerRefId;//The unique ID generated by the payment provider for this transaction

$sourceType=$data->response->sourceType;//The type of party that is providing the funds for this transaction

$destinationType=$data->response->destinationType;//Unique identifier of the party that is receiving funds in this transaction (the Credit Party).

$destination=$data->response->destination;//Unique identifier of the party that is receiving the funds for this transaction.

$description=$data->response->description;//A detailed description of this transaction, including a more detailed failure reason in the case of failures.

$transactionDate=$data->response->transactionDate;//The date and time (according to the payment provider) when a successful transaction was completed.

/*
You can now use the extracted response values above to perform any operation you want.Thats it.Happy coding!!
*/
?>